# Generated by Django 4.2.8 on 2024-01-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('api_key', models.CharField(max_length=32)),
                ('secret_key', models.CharField(max_length=32)),
            ],
        ),
    ]
